spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: auto
    show-sql: false

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

server:
  port : ${PORT:8080}